# Generated by Django 5.1.6 on 2025-04-25 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followerscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(help_text=' Amount of Food Dispensed')),
                ('feed_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FeedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(default='', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('portion_dispensed', models.FloatField(default=0.0)),
                ('success', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('feeding_time', models.TimeField()),
                ('portion_size', models.FloatField()),
            ],
        ),
    ]
